# - Type: Training
#   Trainers: 
#     - Name: Trainer Uno
#       Email: trainer.uno@owasp.org
#       Image: /assets/images/trainers/no-person.png
#       Twitter: forced-request
#       Biography: >-
#         The first trainer of this course is a cybersecurity certified professional with more than 25 years of
#         experience. He works in the field of cybersecurity, cybersecurity research,
#         and threat intelligence.
#       TrainerId: trainer001
#     -Name: Trainer Dos
#       Email: tainer.dos@owasp.org
#       Image: /assets/images/trainers/no-person.png
#       Twitter: Trainer_Dos
#       Biography: >-
#         The second trainer of this course is a cybersecurity certified professional with more than 25 years of
#         experience. He works in the field of cybersecurity, cybersecurity research,
#         and threat intelligence.
#       TrainerId: trainer_dos
#   Title: Training for the Trainable 101
#   URL: 
#   SectionId: sku_IWAHBB
#   Description: >-
#       Training for the trainable. Learn here.
#       <ul>
#       <li>item one</li>
#       <li>item two</li>
#       </ul>   