- Type: Training
  Trainers: 
    - Name: Adam Shostack
      Email: Adam@shostack.org
      Image: /assets/images/trainers/Adam Shostack Photo.jpeg
      Twitter: adamshostack
      Biography: >-
          Adam Shostack is the worlds leading expert in threat modeling. He helped create CVE and is a member of the Blackhat Review Board.
      TrainerId: trainer001
      #-Name: Trainer Dos
      #Email: tainer.dos@owasp.org
      #Image: /assets/images/trainers/staff_harold.jpg
      #Twitter: Trainer_Dos
      #Biography: The second trainer of this course is a cybersecurity certified professional with more than 25 years of
      #  experience. He works in the field of cybersecurity, cybersecurity research,
      #  and threat intelligence.
      #TrainerId: trainer_dos
  Title: Adam Shostacks Threat Modeling Intensive (2-day training course 9am-5pm February 13-14)
  URL: https://www.eventbrite.com/e/owasp-global-appsec-dublin-2023-tickets-428685398567
  SectionId: sku_AS
  Description: >-
      This hands on interactive class will focus on learning to threat model executing each of the steps. Students will start with a guided threat modeling exercise and we will then iterate and break down the skills they are learning in more depth.  We will progress through the Foud Questions of Threat Modeling. What are we working on? What can go wrong? what are we going to do about it and did we do a good job. This is capped off with an end to end exercise that brings the skills together.<br>   
- Type: Training
  Trainers:
    - Name: Konstantinos Papapanagiotou
      Email: kpapapan@styxcyber.com
      Image: /assets/images/trainers/Kostas papapanagiotou.jpg
      Twitter: kpapapan
      Biography: Dr Kostas (Konstantinos) Papapanagiotou is a cyber security consultant that helps organizations around the world improve their security posture. He has more than 20 years of experience in the field of cyber security both as a corporate consultant and as a researcher. Over those years he has led numerous projects ranging from penetration tests to the implementation of complex corporate security, compliance and data loss prevention solutions. He is passionate about teaching and has delivered courses to hundreds of students, security professionals and developers.  He has been involved in OWASP since 2004, leading the OWASP Greek Chapter and several educational initiatives. He is an Adjunct Lecturer at the Hellenic-American University in the field of Cyber Security. He holds a PhD and BSc in Cyber Security from the University of Athens and an MSc in Information Security with distinction from Royal Holloway.
      TrainerID: trainer004
  Title: Securing your applications in AWS & Azure (2-day training course 9am-5pm February 13-14)
  URL: https://www.eventbrite.com/e/owasp-global-appsec-dublin-2023-tickets-428685398567
  SectionId: sku_KP
  Description: >-
      This training provides a thorough introduction to cloud security, covering both AWS and Azure. During the first day, we will go through all you need to know in order to develop and deploy secure applications in AWS. We will present how you can build a secure cloud infrastructure in AWS. You will learn how to use AWS Identity and Access Management in order to manage your users and control access to your resources and data. We will demonstrate how to use AWS-specific tools and features to ensure your application's production data is adequately protected and monitored. By the end of the first day, you should understand how to set up a basic hardened AWS infrastructure capable of deploying a production web application.  During the second day, we will focus on how to build and deploy secure software on the Microsoft Azure cloud platform. You will learn common Azure terminology and the basic components of a secure application architecture in Azure. We will explain how identity and access management work in Azure and how you can leverage Microsoft Identity Platform to manage your users. You will understand how to use Azure-specific features to ensure your application's production data is adequately protected and monitored. By the end of the course, you should understand how to set up a secure infrastructure using Azure, capable of deploying cloud-native web applications and services. 
- Type: Training
  Trainers:
    - Name: Josh Grossman
      Email: josh@bouncesecurity.com
      Image: /assets/images/trainers/josh_headshot_4.jpg
      Twitter: JoshCGrossman
      Biography: >- 
        Josh has worked as a consultant in IT/Application Security and Risk for 15 years now as well as a Software Developer. In that time he has seen the good, the bad and the stuff which is sadly/luckily still covered by an NDA. He is currently Chief Technology Officer for Bounce Security where he spends his time helping organizations improve and get better value from their Application Security processes and providing specialist Application Security advice. In his spare time he co-leads the OWASP Application Security Verification Standard project and is on the OWASP Israel chapter board.
      TrainerId: trainer006
  Title: Building a High-Value AppSec Scanning Programme (2-day training course 9am-5pm February 13-14)
  URL: https://www.eventbrite.com/e/owasp-global-appsec-dublin-2023-tickets-428685398567
  SectionId: sku_JG
  Description: >-
       You bought the application security tools, you have the findings, but now what? Many organizations find themselves drowning in “possible vulnerabilities”, struggling to streamline their processes and not sure how to measure their progress.
        If you are involved in using SAST, DAST or SCA tools in your organization, these may be familiar feelings to you. In this course you will learn how to address these problems and more (in a vendor-neutral way), with topics including:
        <ul>
        <li>What to expect from these tools?</li>
        <li>Customizing and optimizing these tools effectively</li>
        <li>Building tool processes which fit your business</li>
        <li>Automating workflows using CI/CD without slowing it down.</li>
        <li>Showing the value and improvements you are making</li>
        <li>Faster and easier triage through smart filtering</li>
        <li>How to focus on fixing what matters and cut down noise</li>
        <li>Techniques for various alternative forms of remediation</li>
        <li>Building similar processes for penetration testing activities.</li>
        <li>Comparison of the different tool types covered.</li>

        To bring the course to life and let you apply what you learn, you will work in teams on table-top exercises where you design processes to cover specific scenarios, explain and justify your decisions to simulated stakeholders and practice prioritizing your remediation efforts.
        
        For these exercises, you will work based on specially designed process templates (which we will provide) which you can use afterwards to apply these improvements within your own organization.
        
        Be ready to work in a group, take part in discussions and present your findings and leave the course with clear strategies and ideas on how to get less stress and more value from these tools.
- Type: Training
  Trainers:
    - Name: Abraham Aranguren
      Email: admin@7asecurity.com
      Image: /assets/images/trainers/abe_headshot_white.png
      Twitter: 7asecurity
      Biography: >-
        After 15 years in itsec and 22 in IT Abraham is now the CEO of 7ASecurity (7asecurity.com), a company specializing in penetration testing of web/mobile apps, infrastructure, code reviews and training. Co-Author of the Mobile, Web and Desktop (Electron) app 7ASecurity courses. Security Trainer at Blackhat USA, HITB, OWASP Global AppSec and many other events. Former senior penetration tester / team lead at Cure53 and Version 1. Creator of “Practical Web Defense”, a hands-on eLearnSecurity attack / defense course, OWASP OWTF project leader, an OWASP flagship project (owtf.org), Major degree and Diploma in Computer Science, some certs: CISSP, OSCP, GWEB, OSWP, CPTS, CEH, MCSE:Security, MCSA:Security, Security+. As a shell scripting fan trained by unix dinosaurs, Abraham wears a proud manly beard. He writes on Twitter as @7asecurity @7a_ @owtfp or https://7asecurity.com/blog. Multiple presentations, pentest reports and recordings can be found at https://7asecurity.com/publications
      TrainerId: trainer007
  Title: Hacking Modern Web & Desktop Apps (2-day training course 9am-5pm February 13-14)
  URL: https://www.eventbrite.com/e/owasp-global-appsec-dublin-2023-tickets-428685398567
  SectionId: sku_AA
  Description: >-
      This course is a 100% hands-on deep dive into the OWASP Security Testing Guide and relevant items of the OWASP Application Security Verification Standard (ASVS), so this course covers and goes beyond the OWASP Top Ten.
      Long are the days since web servers were run by perl scripts and desktop apps written in Delphi. What is common between Walmart, eBay, PayPal, Microsoft, LinkedIn, Google and Netflix? They all use Node.js: JavaScript on the server. What is common between Microsoft Teams, Skype, Bitwarden, Slack and Discord? All of them are written in Electron: JavaScript on the client.
      Modern Web and Desktop apps share traditional attack vectors and also introduce new opportunities to threat actors. This course will teach you how to review modern web and desktop apps, showcasing Node.js and Electron but using techniques that will also work against any other web or desktop app platform. Ideal for Penetration Testers, Web and Desktop app Developers as well as everybody interested in JavaScript/Node.js/Electron app security.
      All action, no fluff, improve your security analysis workflow and immediately apply these gained skills in your workplace, packed with exercises, extra mile challenges and CTF, self-paced and suitable for all skill levels, with continued education via unlimited email support and lifetime access to training portal with step-by-step video recordings and interesting apps to practice, including all future updates for free.
- Type: Training
  Trainers:
    - Name: Fabio Cerullo
      Email: fcerullo@cycubix.com
      Image: /assets/images/trainers/Fabio Cerullo.jpg
      Twitter: fcerullo
      Biography: >-
        Fabio delivered this training to thousands of developers and security professionals. He also regularly delivers training to technical audiences on various topics such as application security, cloud security, and information security. Here is a reference from one attendee of his courses: <quote>Fabio is an excellent instructor. I was lucky enough to attend one of the courses where he was the instructor. He was able to present the subject matter in an interesting way and at an appropriate pace. He encouraged interaction and was able to answer questions with ease by leveraging his extensive experience in the industry.</quote>
        Fabio Cerullo is an official certified instructor for (ISC)², the global leader in information security education and certification. He is also an AWS authorized instructor covering architecting and security topics. Fabio has over 15 years of experience in the information security field gained across a diverse range of industries ranging from financial and government institutions to software houses and start-ups. He regularly trains professionals from different backgrounds in application security, cloud security, and information security. He is a regular speaker at events organized by OWASP, ISACA and (ISC)² among others; and provides commentary and written articles for specialized industry media (Computer Weekly, Infosecurity Magazine, SiliconRepublic.com, etc). He holds an MSc in Computer Engineering from UCA, the SSCP, CISSP, CSSLP & CCSP certifications from (ISC)² and the AWS Certified Solution Architect certification.
      TrainerId: trainer008
  Title: Web Application Security Essentials (2-day training course 9am-5pm February 13-14)
  URL: https://www.eventbrite.com/e/owasp-global-appsec-dublin-2023-tickets-428685398567
  SectionId: sku_FC
  Description: >-
        This course provides the knowledge and resources required to evaluate the security of web applications. The participants, through the understanding of theory and a strong focus on practical exercises, will be able to identify critical vulnerabilities in web applications, understand how exploitation works and learn how to implement the necessary corrective measures.
        The course is aligned with the OWASP 10 2021, a world-renowned reference document which describes the most critical web application security flaws.
        <br>
        The topics covered include:
        <ul>
        <li>Introduction to Web Application Security</li>
        <li>Technologies used in Web Applications</li>
        <li>The Security Tester Toolkit</li>
        <li>Critical Areas in Web Applications</li>
        <li>Broken Access Control</li>
        <li>Cryptographic Failures</li>
        <li>Injection</li>
        <li>Insecure Design</li>
        <li>Security Misconfiguration</li>
        <li>Vulnerable and Outdated Components</li>
        <li>Identification and Authentication Failures</li>
        <li>Software and Data Integrity Failures</li>
        <li>Security Logging and Monitoring Failures</li>
        <li>Server Side Request Forgery (SSRF)</li>
        </ul>
        Format: The course combines theory and hands-on practical exercises. The participants start by learning about web application vulnerabilities. They are then given access to a purpose-built web application environment that contains the bugs and coding errors they have learned about. This provides an ideal ‘real-life’ opportunity to exploit these vulnerabilities in a safe environment.     
- Type: Training
  Trainers:
    - Name: Sven Schleier
      Email: sven.schleier@owasp.com
      Image: /assets/images/trainers/sven_headshot.png
      Twitter: bsd_daemon
      Biography: >-
        Sven is the Technical Director of WithSecure in Singapore, specialized in penetration testing and application security.  Next to offensive security engagements he has supported and guided software development projects for Mobile and Web Applicatioins during the Whole SDLC to build security in from the start. Besides his day job Sven is one of the core project leaders and authors of the OWASP Mobile App Security Testing Guide and OWASP Mobile Application Security Verification Standard and has created the OWASP Mobile Hacking Playground. Sven is giving talks and workshops about Mobile Security worldwide to different audiences, ranging from developers to students and penetration testers.
      TrainerId: trainer009
  Title: Mobile Security Testing Guide – hands-on
  URL: https://www.eventbrite.com/e/owasp-global-appsec-dublin-2023-tickets-428685398567
  SectionId: sku_SS
  Description: >- 
        This course teaching you how to analyze Android and iOS apps for security vulnterabilities by going through the different phases of testing including dynamic testing, static analysis and reverse engineering.  Sven will share his experience and many small tips and tricks to attack mobile apps that he collected throughout his career and bug hunting adventures. The beginning of the first day we start by giving an overview of the Android Platform and its Security Architecture.  It is no longer madatory for studens to bring their own Android device, instead a cloud based virtualized Android device will be provded for each student by using Corellium.
        <br>
        <p>These are some of the topics that will be covered during the course: 
        <ul>
        <li>Frida crash course to kick start with dynamic instrumentation on Android Apps</li>
        <li>Intercepting network traffic of apps written in mobile app frameworks such as Googles Flutter</li>
        <li>Identifying and exploiting a real world Deep link vulnterability</li>
        <li>Explore the differences and effectiveness of Reverse Engineering Andoid Apps through patching Smali, Xposed and Dynamic Instrumentation with Frida</li>
        <li>Analyze Local Storage of an Andoid App</li>
        <li>Using Frida to bypass End2End Encrypitoin in an Android App</li>
        <li>Usage of dynamic instrumentation with Frida to bypass Frida detection mechanisms and bypass multiple root detection mechanisms</li>
        <section>
        <p>On day 2 we are focusing on iOS and will begin with an overview of the iOS Platform and Security Architecture.  After explaining what an IPA container and the iOS file system structure we start creating an iOS test environment with Corellium and deep dive into various topics, including:
        <ul>
        <li>Analyzing iOS applications that use non HTTP traffic including ways of intercepting the traffic</li>
        <li>Frida crash course to kick start with dybamic instrumentation of iOS apps</li>
        <li>Bypassing SSL Pinning with SSL Kill Switch and Objection</li>
        <li>Testing methodology with a non jailbroken device by repackaging an IPA with the Frida Gadget</li>
        <li>Testing stateless authentication mechanisms such as JWT  in an iOS application</li>
        <li>Using Frida for Runtime Instrumentation of iOS apps to bypass Anti Jailbreaking mechanisms, Frida detection mechanism, and other client side security controls
        <section>
        <p>The course consists of many different labs developed by us and the course is roughtly half hands on and half lecture. At the end of each day a small CFT will be played to investigate an app with the newly learned skills and there will be prizes. After a successful completion of this course students will have a better understading of how to test for vulnerabilities in mobil apps, how to mitigate them and how to execute tests consistantly.  The course is based on the OWASP Mobile Security Testing Guide and is conducted by one of the authors himself. The OWASP MSTG is a comprehensive and open source guide about mobile security testing for both iOS and Android. 
        </ul>
        <p>The following prerequisites need to be fulfilled by the students in order to be able to follow all exercises and fully participate:
        <ul>
        <li>Laptop, Window, Linux, or MacOS with at least 8 GB Ram and 40 GB of free disk space</li>
        <li>Full admistrative access, in case of any issues with the lalptop environment</li>
        <li>Virtualization software; a VM will be provided as OVA with all tools needed for the training</li>
        <section>
        <p>An iOS and Android device is not needed, as an emulated instance will be provided for each student that is hosted in Corellium. this is a cloud based environment that allows each student access to a jailbroken iOS device and rooted Android device during the training.
        
